service: gogramda

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2

package:
  exclude:
  - ./**
  include:
  - ./bin/**
  - ./schema/**

functions:
  graphql:
    handler: bin/graphql
    events:
    - http:
        path: /
        method: get
        cors: true
        integration: lambda-proxy
    - http:
        path: /
        method: post
        cors: true
        integration: lambda-proxy
